updates [skip ci]

diff --git a/am-apt-update b/am-apt-update
--- a/am-apt-update
+++ b/am-apt-update
@@ -1,17 +1,17 @@
 #!/bin/bash
 # set -o errexit      # -e, exit if error occurs
-set -o nounset      # -u, treat unset variables and parameters as an error
-set -o pipefail     # fail if pipe failed
-# set -x
+# set -o nounset      # -u, treat unset variables and parameters as an error
+# set -o pipefail     # fail if pipe failed
+set -x
 #
 _curl () {
-	set +o nounset
+	# set +o nounset
 	if [ -n "${3}" ]; then echo "Getting - ${3}"; fi
-	set -o nounset
-	set +o errexit
+	# set -o nounset
+	# set +o errexit
 	curl -sL -f -o "${2}" "${1}"
 	_curlError="$?"
-	set -o errexit
+	# set -o errexit
 	if [ "${_curlError}" -ne 0 ]; then
 		echo "Curl Error - ${3:-${1}}"
 	fi
@@ -30,8 +30,6 @@ get_packages () {
 	touch apt.json
 
 	for i in $( jq -r '. | select( .distro=="apt" ).name' <<< "${_distros}" ); do
-set -x
-cat apt.json
 		# if ! jq -e --arg _name "${i}" '. | select ( .name==$_name ).version' apt.json > /dev/null 2>&1; then
 		jq -e --arg _name "${i}" '. | select ( .name==$_name ).version' apt.json > /dev/null 2>&1
 		if [ $? -ne 0 ]; then
@@ -52,7 +50,6 @@ cat apt.json
 		else
 			echo "Error - ${i} ${_new_version}"
 		fi
-set +x
 	done
 
 	popd >/dev/null
